# Generated by Django 2.0.2 on 2018-02-19 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 15, 53, 10, 228868)),
        ),
    ]
