# Generated by Django 2.0.2 on 2018-02-19 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journal_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 17, 40, 25, 230812)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 17, 40, 25, 230785)),
        ),
    ]
