# Generated by Django 2.0.2 on 2018-02-19 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180219_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 17, 41, 14, 620764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 17, 41, 14, 620797, tzinfo=utc)),
        ),
    ]
